### ISSUE TITLE
bug: IDE experience incorrectly flags `inherit` constructor chaining where no vals

### ISSUE THREAD

**Issue by bartelink** [JetBrains/resharper-fsharp#554]
Using  2022.3.3 on a Mac, the IDE flags an (admittedly esoteric) bit of syntax, that compiles fine:
<img width="1104" alt="image" src="https://github.com/JetBrains/resharper-fsharp/assets/206668/d0636fc0-1757-4b15-973b-29262f4a7c76">
(if I add a dummy `val`, it works fine)

References:
- https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/inheritance
- https://stackoverflow.com/questions/75900935/f-add-multiple-constructor-overloads-that-call-the-base-class-constructor
- https://github.com/fsharp/fslang-suggestions/issues/1302 (triggered me to try it)

**Comment by auduchinok** [comment]
@bartelink Hi, thank you for reporting it. Could you please check it on 2023.2 release? It should be fixed there.

**Comment by bartelink** [comment]
Thanks, doh! (I was distracted by `on March 20, 2023` in the about and didn't even consider I could be that far behind)
Closing; will necropost if it turns out this still repros

**Comment by bartelink** [comment]
Unfortunately I'm still seeing it in 2023.2
If you replace `EventStoreCategory` in https://github.com/jet/equinox's `master` with
```
type EventStoreCategory<'event, 'state, 'context> =
    inherit Equinox.Category<'event, 'state, 'context>
    new(context: EventStoreContext, name, codec: FsCodec.IEventCodec<_, _, 'context>, fold, initial, access, caching) =
        { inherit Equinox.Category<'event, 'state, 'context>(name,
            Category<'event, 'state, 'context>(context, codec, fold, initial, access)
            |> Caching.apply Token.isStale caching) }
```
it's still asserting '`this record contains fields from inconsistent types`', despite it compiling...
As mentioned, changing it to:
```
type EventStoreCategory<'event, 'state, 'context> =
    inherit Equinox.Category<'event, 'state, 'context>
    val dummy: int
    new(context: EventStoreContext, name, codec: FsCodec.IEventCodec<_, _, 'context>, fold, initial, access, caching) =
        { inherit Equinox.Category<'event, 'state, 'context>(name,
            Category<'event, 'state, 'context>(context, codec, fold, initial, access)
            |> Caching.apply Token.isStale caching); dummy = 1 }
```
shuts it up
(The `ids` branch applies a few more in the most recent commit, but they are all equivalent in that they don't have any `val`s to initialize etc)

**Comment by auduchinok** [comment]
@bartelink Thanks for checking! Yes, indeed, it's actually fixed in 2023.3 builds, not in 2023.2. There was an issue in the initial implementation of https://github.com/dotnet/fsharp/pull/15214 in our FCS work, and I've fixed it when proposed the change upstream.

2023.2:

<img width="963" alt="Screenshot 2023-08-08 at 12 00 53" src="https://github.com/JetBrains/resharper-fsharp/assets/3923587/b1470fbd-a711-4f75-88e9-a0a8787bf08c">

2023.3:

<img width="955" alt="Screenshot 2023-08-08 at 12 01 40" src="https://github.com/JetBrains/resharper-fsharp/assets/3923587/fb6e5ea5-534d-4b7b-904f-e938736e6b75">

I'll see if it's safe to backport it to a bug fix release.

**Comment by bartelink** [comment]
> I'll see if it's safe to backport it to a bug fix release.

Please don't; I'll wait

**Comment by auduchinok** [comment]
@jwosty Thanks for reporting it! Yes, all looks good in 2023.3:
<img width="1182" alt="Screenshot 2023-11-16 at 20 58 08" src="https://github.com/JetBrains/resharper-fsharp/assets/3923587/adef435d-b016-4ae8-95b1-643e52e5b6bf">
